dbt_currency_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: admin
      port: 5432
      dbname: postgres
      schema: msd_financial_dbt
      threads: 1
